version: "3"

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask
    volumes:
      - ./flask/logs:/usr/src/flask_app/logs
    ports:
      - "16983:8003"
    command: gunicorn -c ./gunicorn.conf.py 'app:create_app()'

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8083:80"
    depends_on:
      - flask_app
