SUCCESS = 200  # GET - DATA OR EMPTY LIST
CREATED = 201  # POST
NO_CONTENT = 204  # DELETE, PUT
FAIL = 400  # GENERAIL FAIL - CLIENT ERROR
NO_AUTH = 401  # LOGIN NEEDED
FORBIDDEN = 403  # ADMIN ONLY
NOT_FOUND = 404  # NOT FOUND BY IDENTIFIER
SEVER_ERROR = 500  # SEVER ERROR
